### ISSUE TITLE
PCB problems

### ISSUE THREAD

**Issue by sergiocro** [OpenSprinklerBee/OSBeeWiFi-Hardware#1]
Hi ... 

first of all great work, tahnk you for made it open source ...

I have discovered some errors in PCB design ... can you please check that osbee_3.0.brd and osbee_3.0.sch are ok ...

thank you

**Comment by sergiocro** [comment]
<a href="https://postimg.cc/wyn9GJmr" target="_blank"><img src="https://i.postimg.cc/wyn9GJmr/err1.png" alt="err1"/></a><br/><br/>
<a href="https://postimg.cc/tZsXkDYP" target="_blank"><img src="https://i.postimg.cc/tZsXkDYP/err2.png" alt="err2"/></a><br/><br/>

**Comment by sergiocro** [comment]
so there is no chance to get updated PCB ?

**Comment by rayshobby** [comment]
The first image is not a mistake: it's thermo-isolation of a ground pin. The second image, I don't know how you generated this, or which version of EagleCAD you were using, but this is NOT in the OSBee circuit. I attached what shows up in my EagleCAD. 
![Screenshot from 2024-06-02 08-47-14](https://github.com/OpenSprinkler/OSBeeWiFi-Hardware/assets/1017684/cb1aca80-e933-4eb4-a440-386c5fdb8657)

**Comment by sergiocro** [comment]
Im using autodesk fusion ... first image is showing that GPIO0 is conected to GND ? same thing like on second image where D+ is conecded to GND ... can you plese check that you have same file like on Github. thanks

**Comment by sergiocro** [comment]
and this are imgs from pcbway from original osbee_3_2023-05-27 GREB file

![pcb_W1](https://github.com/OpenSprinkler/OSBeeWiFi-Hardware/assets/71232756/c449a7d2-9c9a-4876-b5d9-7a4c9ff3700f)
![pcb_W2](https://github.com/OpenSprinkler/OSBeeWiFi-Hardware/assets/71232756/ce8fd085-7f29-4673-90ba-5150e9559847)
